- README.md
- main.go
- Rename existing exit code constants to explicitly note that
they are exit codes.
- This is a BREAKING change, but according to godoc.org there
is only one consumer of this package thus far and it is one
that I maintain (PR incoming there soon)
- Add constants for state "labels" to help reduce typos when
referencing output text strings like "OK", "WARNING", etc.
I believe that further refinement is needed here once I better
understand the various use cases.
fixes GH-16
> BREAKING: Add state labels, rename existing consts

- nagios.go
Conditionally display provided thresholds, or note that they are not defined. This prevents empty list items from showing in the `Long Service Output` section. Without an explicit value of some kind, it gives the impression that a bug has prevented the information from showing.
fixes GH-37
> Do not assume that state thresholds will be given

- nagios.go
Previously some section headers used 2x EOL chars, while
others used a single EOL. This changed the requirement for
client-provided values based on what setting was being
specified.
This commit attempts to make the formatting consistent for
each subsection. Further adjustments may be necessary once
client code is updated to accomodate these changes.
fixes GH-41
> Use consistent EOL format in Long Service Output

- README.md
- nagios.go
- Change receiver type to allow early deferral of method
before field values have been fully set.
- Update documentation to heavily emphasize early deferral
registration in order to allow other deferred functions to
run as intended.
fixes GH-44
> Update method to work properly when deferred

- README.md
- nagios.go
Handle panics within `ReturnCheckResults()` instead of leaving this entirely up to client code to handle. As
part of this, override the `ExitState` fields in order to prominently display panic details in place of `LongServiceOutput` details normally shown if set by the plugin client code.
fixes GH-49
> Explicitly catch panics, override ExitState fields

- .markdownlint.yml
At some point I made a search/replace operation that
unintentionally replaced the `//` characters in the project
URL with a hash mark.
I seem to have caught/corrected the other cases, but this one
was left behind.
Minor fix to sort that.
> Fix breadcrumb URL

- nagios.go
Treat `ServiceOutput` field content as preformatted text, skipping potential false-positive handling of literal values
as formatting verbs. In particular, this avoids treating lone `%` values as a formatting verb prefix.
fixes GH-58
> Explicitly emit ServiceOutput as-is

- nagios.go
- Emit as first line item in pre block above stack trace
- Emit as part of error entry
Not including as one of one-line summary on the chance that
the panic message is overly long.
fixes GH-61
> Expose panic error message

- nagios.go
Because Nagios strips out angle brackets, we're unable to effectively use `pre` tags so we fall back to an attempt to use Markdown code fences instead.
fixes GH-69
> Replace pre tags with Markdown code fences

- nagios.go
There have been several cases where not having the full
stack trace has hindered troubleshooting efforts, so opting
to return the complete trace instead of a truncated snippet.
This behavior is subject to change again in the future (e.g.,
if some massive trace is captured and reported causing
further issues).
fixes GH-68
> Provide complete stack trace instead of snippet

- nagios.go
Credit: Code Spell Checker VSCode extension.
fixes GH-82
> Fix typo in UNKNOWN state label constant

- nagios.go
This type provides a state Label and ExitCode.
Port this type from the atc0005/check-cert project to allow broader use.
fixes GH-80
> Add ServiceState type

- CHANGELOG.md
Accidentally duplicated the v0.6.1 tag ref link text.
> Fix typo in CHANGELOG release tags list

- nagios.go
Stress using underscores to match community naming convention.
refs GH-81
> Clarify Label field naming convention

- nagios.go
- Fix `skipValidation` flag handling behavior
- Skip appending any performance data if a validation failure occurs
- Update doc comments to make expected behavior clear
refs GH-81
> Fix broken validation handling behavior

- nagios.go
This commit removes the package doc comment from `nagios.go`, leaving the lead-in doc comment in `doc.go` to provide that coverage.
fixes GH-91
> Remove duplicate package doc comment

- nagios.go
Emit Performance Data when available AND when `ServiceOutput` is set. This guards against emitting metrics when there isn't valid (complete) plugin data to process.
- fixes GH-98
- refs atc0005/check-vmware#473
> Only emit Performance Data when (complete) plugin data present

- nagios.go
This change accounts for the potential to receive an empty slice in addition to a nil slice (as we were checking for prior to this change).
fixes GH-104
> Use length check for perfdata instead of nil check

- nagios.go
This appears to give the intended results for both Nagios Core
and Nagios XI. Presumably other monitoring systems are similarly
compatible with this change.
fixes GH-109
> Switch from DOS EOL to UNIX EOL, add leading space

- nagios.go
Commit f0c9c497bfccbdfc0e4a3dc5d45efeffd93cd054 applied an
incorrect interpolation order for the (potentially custom)
section header/label values.
This commit updates the order so that the label text is placed
within the formatting characters as intended.
- fixes GH-107
- refs GH-119
> Fix incorrect interpolation order for labels

- nagios.go
- sections.go
Satisfy gocognit linter, but also (hopefully) make the code easier to maintain going forward.
fixes GH-127
> Split ExitState.ReturnCheckResults() into helpers

- sections.go
Update func `(ExitState).handleLongServiceOutput` to return early to prevent emitting header for empty content collection.
fixes GH-132
> Exit early if no `LongServiceOutput` to process

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint-and-build-code.yml
- .github/workflows/lint-and-test-only.yml
- .github/workflows/lint-docs.yml
- .golangci.yml
- Makefile
- echo hadolint version
- echo golangci-lint version
- echo staticcheck version
- echo markdownlint-cli version
- add `go_mod_changes` job to test for uncommitted `go mod tidy`
and `go mod vendor` changes
- update repo-bundled golangci-lint configuration to replace (most)
deprecated linters
- `golint` to `revive`
- `scopelint` to `exportloopref`
- enable additional linters that I already use within the
atc0005/go-ci stable images.
- `govet`
- `staticcheck`
- add CodeQL GitHub Actions Workflow
> Update Makefile and GitHub Actions Workflows

- nagios.go
Fix unintentional handling of Service Output from client code as potentially containing formatt specifier (i.e., formatting "verbs") by explicitly emitting content as-is.
This fixes a regression introduced by the v0.9.0 release that was introduced by bulk refactoring work.
- fixes GH-139
- refs GH-58
> Emit `Service Output` as-is

- nagios.go
- sections.go
- unexported_test.go
Apply a series of changes to help prevent further regressions:
- move Service Output handling logic to helper function
- consolidate logic in one place similar to how the other output sections (e.g., Errors, Long Service Output) are already handled to make this logic easier to test
- add test case
- intentionally restore regression by using `fmt.Fprintf` function in helper code
- fix regression by using `fmt.Fprint` as intended, confirm expected behavior
- GH-58
- GH-139
> Prevent further Service Output interpolation regressions

- nagios.go
Add ExitState.SetOutputTarget method to provide client code the ability to override the destination output sink. This could be used to redirect output to a file, a tee writer or an in-memory buffer for test purposes.
Default to os.Stdout if user does not specify a custom output sink.
fixes GH-140
> Add support for setting preferred output target

- exported_test.go
- go.mod
- go.sum
- testdata/README.md
- testdata/plugin-output-datastore-0001.txt
- vendor/github.com/google/go-cmp/LICENSE
- vendor/github.com/google/go-cmp/cmp/compare.go
- vendor/github.com/google/go-cmp/cmp/export_panic.go
- vendor/github.com/google/go-cmp/cmp/export_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
- vendor/github.com/google/go-cmp/cmp/internal/function/func.go
- vendor/github.com/google/go-cmp/cmp/internal/value/name.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
- vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
- vendor/github.com/google/go-cmp/cmp/options.go
- vendor/github.com/google/go-cmp/cmp/path.go
- vendor/github.com/google/go-cmp/cmp/report.go
- vendor/github.com/google/go-cmp/cmp/report_compare.go
- vendor/github.com/google/go-cmp/cmp/report_references.go
- vendor/github.com/google/go-cmp/cmp/report_reflect.go
- vendor/github.com/google/go-cmp/cmp/report_slices.go
- vendor/github.com/google/go-cmp/cmp/report_text.go
- vendor/github.com/google/go-cmp/cmp/report_value.go
- vendor/modules.txt
I hesitate to call this a true End to End (e2e) test, but this initial test configures an ExitState value as client code in the wild currently does and then asserts that the output matches the contents of a carefully crafted testdata file.
NOTE:
This test adds a dependency on the popular `github.com/google/go-cmp` testing package. 
Because future tests are planned which will also use this package, adding the dependency (only for tests) is deemed to be worth the "cost" of adding an external dependency (again, just for tests).
> Add initial plugin output test

- exported_test.go
- sections.go
- testdata/plugin-output-gh103-multi-line-with-perf-data.txt
- testdata/plugin-output-gh103-one-line-with-perf-data.txt
If `LongServiceOutput` is set, emit Performance Data after it as previously done. Otherwise, if not set, emit Performance Data immediately after ServiceOutput.
Add tests and testdata to assert the expected behavior.
fixes GH-103
> Emit perfdata on same line as ServiceOutput if

- unexported_test.go
Add test to ensure that an empty collection of performance data produces no output (and no errors).
> Assert that empty perfdata produces no output

- example_emit_perfdata_via_deferred_function_test.go
- exported_test.go
- unexported_test.go
Missed some references in test names, example code.
> Replace further ExitState references

- README.md
- nagios.go
- range.go
- range_test.go
Minor changes applied as a follow-up to PR #178:
- concentrate new Range functionality in dedicated files
- this reflects similar work underway for GH-175
- update README
- mention new Range support
- link to dependent projects (including one from contributor of new functionality)
- doc comment tweaks
- misc changes to satisfy current CI linters
- @infraweavers (https://github.com/infraweavers)
- https://github.com/atc0005/go-nagios/pull/178
- fixes GH-176
-  GH-178
> Refactor newly added Range support

- unexported_test.go
Test began failing with work on PR branch for PR-175 which expanded validation support for PerformanceData field values.
The previous test metric values used words in place of expected field values:
- literal "U"
- character or values in the regex character class "[-0-9.]"
This commit moves the self-documenting Value field strings to slice element comments and replaces them with placeholder numeric values which pass Value field validation.
refs GH-175
> Fix TestPerformanceDataIsNotDuplicated test

- perfdata.go
Use helper validation functions implemented for earlier work to expand validation of PerformanceData fields.
This is not expected to be a breaking change as it adjusts validation behavior to assert valid performance data metric field values per official plugin guidelines.
fixes GH-186
> Expand PerformanceData field validation

- perfdata_test.go
Borrow output from an updated plugin in the atc0005/check-cert project.
Also, minor tweak to existing table test case name.
> Add another perfdata success parsing test case

- example_constants_test.go
- perfdata.go
- Split `Example_usingOnlyTheProvidedConstants` function to resolve `unreachable-code` linting error
- Fix `if-return` revive linting error
> Fix revive linting errors

- nagios.go
These functions return a collection of all supported values:
- `SupportedStateLabels`
- `SupportedExitCodes`
- `SupportedServiceStates`
These functions serve as lookup helpers to map a given value to its corresponding value:
- `StateLabelToExitCode`
- `ExitCodeToStateLabel`
> Add state lookup helper functions

- nagios.go
Emphasize that the AddError method does not deduplicate errors when adding to the collection.
fixes GH-212
> Clarify (nagios.Plugin).AddError behavior

- nagios.go
- textutils.go
In contrast to `Plugin.AddError` which does not provide deduplication of errors before growing the collection, the `Plugin.AddUniqueError` method *does* provide deduplication.
The dedupe behavior is provided by case-insensitive comparison of the error string for the provided error against existing errors already in the collection.
fixes GH-214
> Provide `Plugin.AddUniqueError` with dedupe behavior

- annotations.go
- package level `AnnotateError` function
- multiple `nagios.Plugin` methods
- `AddAnnotatedError`
- `AddUniqueAnnotatedError`
- `AnnotateRecordedErrors`
- package level `DefaultErrorAnnotationMappings` function to provide the default error to advice map to calling/client code (e.g., to override with custom advice specific to that project)
This collection of changes provides a way for client code to add additional human-readable explanation for errors encountered during plugin execution. This additional context is intended to help sysadmins remediate common issues detected by plugins.
- fixes GH-209
> Add support for error annotations

- exported_test.go
Add nolint directive to permit duplicate `plugin.ServiceOutput` content between test cases.
> Hotfix goconst linting errors for test cases

- nagios.go
- range.go
- range_test.go
this PR adds checking of nil returns from ParseRangeString in EvaluateThreshold. it returns UNKNOWN state result and an error message.
second I added 2 tests to check this expected behavior
fixes #233, replace #234
> Fix panic if ParseRangeCheck returns nil

- range.go
> Update Range Check regexp

- perfdata_test.go
Add test case for lifetime metrics which uses `%` UoM.
NOTE:
As of this writing the plugin does not emit threshold values for this metric so our test case does not specify thresholds either. If thresholds are provided in the future for this metric we should update this test case OR add an additional test case which specifies thresholds.
> Add check_cert plugin perfdata success test case

- exported_test.go
- nagios.go
- sections.go
Resolve `return value of fmt.Fprintf is not checked`` errors by explicitly discarding return values (potential error, bytes written) since we do not need them and the potential for failure (in this particular use case) is *highly* unlikely.
The one exception is `Plugin.emitOutput`. There, we capture the potential error and emit a message to os.Stderr if an error occurs. If that attempt fails (however unlikely) we panic.
> Fix errcheck linting errors

- unexported_test.go
This test unintentionally copy/pasted/modified from another test but stopped short of completing the work.
- handle setting up ServiceOutput section instead of the performance data metrics output
- update OK message when test completes successfully
> Fix `TestEmptyServiceOutputProducesNoOutput` test

- perfdata.go
Replace use of `min` and `max` variables with longer names to avoid conflicts with `min` and `max` functions introduced in Go 1.21.
Update similar variables in the same scope to match updated naming pattern.
> Fix `predeclared` linter warnings

- nagios.go
- unexported_test.go
- Add test cases for `Plugin.SetOutputTarget`
- `TestPluginSetOutputTargetIsValidWithValidInput`
- basic assertion to show that the method works as intended with valid/expected input
- TestPluginSetOutputTargetIsValidWithInvalidInput
- asserts that when given an invalid output target that the default/fallback output target is used instead
- Fix `Plugin.SetOutputTarget` fallback behavior
- correctly fallback to default output target when an invalid output target is provided
- fixes GH-267
> Fix `Plugin.SetOutputTarget` method

- nagios.go
- unexported_test.go
Update `TestPluginSetOutputTargetIsValidWithInvalidInput` to not just assert that plugin.outputSink is set when an invalid output target is specified, but also that it is specifically set to the default plugin output target as intended.
- refs GH-268
- refs GH-267
> Fix test case validity check

- range.go
Swap separate if statements for switch statement to reduce gocognit linter score. Overall this doesn't do much, but an upside is that it does group prefix checks in one place.
> Minor refactoring of ParseRangeString func

- range.go
Refactor the following methods/functions used to provide `Range` and `Thresholds` support with the assistance of Google Gemini and OpenAI's ChatGPT:
- `(Range).checkOutsideRange`
- replace existing method with implementation provided by Google Gemini (model 'Gemini 1.5 Flash')
- include commented out alternative implementation from ChatGPT (model 'GPT-4o') for contrast
- `ParseRangeString`
- rework existing function with suggested changes from ChatGPT (model 'GPT-4o') with an additional small adjustment to reduce the gocognit linter score further
- `Plugin.EvaluateThreshold`
- replace existing method with implementation provided by ChatGPT (model 'GPT-4o'), including closure which was moved to separate `evaluateThreshold` helper function
- GH-278
> Minor refactoring of Range and Thresholds support

- nagios.go
- unexported_test.go
Make changes to clarify what happens when empty input is provided to encoded payload methods.
- update doc comments and behavior of payload related methods to explicitly handle empty input vs using previous implicit behavior of underlying buffer field
- `(Plugin).AddPayloadBytes`
- `(Plugin).AddPayloadString`
- `(Plugin).SetPayloadBytes`
- `(Plugin).SetPayloadString`
- add new tests to lock-in the intended behavior for empty input for those payload related methods
- `TestAddPayloadString_AppendsNothingWhenCalledWithEmptyInput`
- `TestAddPayloadBytes_AppendsNothingWhenCalledWithEmptyInput`
- `TestSetPayloadString_SetsInputSuccessfullyWhenCalledWithEmptyInput`
- `TestSetPayloadBytes_SetsInputSuccessfullyWhenCalledWithEmptyInput`
- GH-251
> Clarify handling of empty payload input

- sections.go
Add `p.logAction` calls to early exit points within each applicable section handler to make troubleshooting unexpected results involving empty input easier.
refs GH-271
> Log early exit behavior for section handlers

- sections.go
If encoded payload content is provided then enable the LongServiceOutput section header/label to better separate the two types of output/content.
refs GH-251
> Enable LongServiceOutput header/label for payloads

- payload.go
Brief testing shows that when the encoded Ascii85 payload passes through the Nagios XI (JSON) API that the backslash character is escaped. Instead of handling this client-side we extend the decoding process to automatically handle unescaping that pattern. This also provides a "hook" for further unescaping if other monitoring systems apply similar escaping of the encoded payload.
Also, fix various typos in doc comments not caught during previous polishing passes.
refs GH-251
> Unescape encoded Ascii85 payload before decoding

- sections.go
Replace indicators of writing to a buffer (something the logging calls can't know) with writing to a given output sink (which matches the language used nearby.
> Update `logPluginOutputSize` calls for consistency

- README.md
Note that transparent compression/decompression is now performed when managing payloads.
Drop explicit mention of Ascii85 as encoding format. While we continue to use it, the specifics are less important.
refs GH-301
> Update README to note payload behavior changes

- README.md
Clarify that support is available to extract a payload from given input *without* decoding and decompressing the contents in addition to the all-in-one behavior (of performing all of those steps) available as a separate function.
refs GH-301
> Update README to correct redundant statement

- exported_test.go
- testdata/plugin-output-multiline-with-optional-perf-data-included.txt
- testdata/plugin-output-one-line-with-optional-perf-data-included.txt
- rename existing one-line and multi-line performance data metric tests to reflect that they're testing for default performance data metrics
- add new testdata input files for "all optional" performance data metrics tests
- add new tests intended to assert that all optional performance data metrics are emitted *and* that the plugin output size is properly calculated
- later refactoring willl likely lead to separating these two goals into different tests
refs GH-324
> Add tests for plugin output size

- go.mod
The `github.com/google/go-cmp` dependency bumped its minimum Go version from Go 1.13 to 1.21 as of the v0.7.0 release.
Since this project depends on it, we either have to also bump the minimum Go version or find a way to move all tests into a separate module. Since some tests currently access unexported values (fields, methods, functions, etc.), this won't be a simple change.
For now, bumping the minimum Go version is the easiest path forward.
- GH-341
> Bump minimum Go version from 1.19 to 1.21

- sections.go
Per linter output:
> if block ends with call to panic function, so drop this else and outdent its block (revive)
> Fix `superfluous-else` revive linter error
